### ISSUE TITLE
Sidebar links no longer highlight in response to content area scroll position

### ISSUE THREAD

**Issue by dominicnguyen** [meteor/hexo-theme-meteor#10]
**Current behavior**
When scrolling the content area the sidebar links no longer highlight via an `.active` class. This is a regression.

**Expected behavior**
When scrolling the sidebar links get an `.active` class. See image:
<img width="254" alt="screenshot 2016-05-20 18 01 29" src="https://cloud.githubusercontent.com/assets/263385/15443286/1b858f1e-1eb5-11e6-89a4-45e0c56af22e.png">

**Comment by tmeasday** [comment]
This was working a little bit ago. What changed?

**Comment by tmeasday** [comment]
Wanna try a `git bisect` ;) ?

**Comment by tmeasday** [comment]
Fixed.
