### ISSUE TITLE
Change default menu scrollTop?

### ISSUE THREAD

**Issue by lorensr** [meteor/hexo-theme-meteor#11]
Right now, after pageload, it's set to:

![2016-05-20 21 52 56](https://cloud.githubusercontent.com/assets/251288/15445797/befbc4d6-1ed5-11e6-9de4-6ad1677af0be.png)

A little higher would look nicer to me:

![2016-05-20 21 53 10](https://cloud.githubusercontent.com/assets/251288/15445799/cace5634-1ed5-11e6-9efd-04932af7622a.png)

**Comment by dominicnguyen** [comment]
Agree. It doesn't seem easy to preserve state from one page to the next due to page refreshes. I think the sidebar scrolling policy should revert back to not scrolling to the section in the sidebar because it obfuscates the title of the sidebar when landing on the site. @tmeasday what do you think?

**Comment by lorensr** [comment]
I like the scrolling for everything but the root. For instance on command line page, when I open the menu, I'm more likely to want to find a particular command, and if menu scrollTop was 0, I wouldn't even see that section, so current behavior is nice:

![2016-05-23 12 44 04](https://cloud.githubusercontent.com/assets/251288/15477736/48324d46-20e4-11e6-97da-ede2ce83202b.png)

**Comment by tmeasday** [comment]
Yeah I added this to deal with exactly the problem @lorensr describes: https://github.com/meteor/hexo-theme-meteor/commit/a6143b95d7726ec263192b01a0f44adb516d2d45

Should we put an if there to check if it's the first link?

**Comment by abernix** [comment]
This is causing the new search box to be off the top of the page by default (the search box needs it's own search box to find it!).

**Comment by tmeasday** [comment]
Fixed, let me know what you think.

**Comment by abernix** [comment]
Perfect to me @tmeasday.
