### ISSUE TITLE
Further differentiate h2s and h3s

### ISSUE THREAD

**Issue by lorensr** [meteor/hexo-theme-meteor#17]
From https://github.com/meteor/guide/issues/463#issuecomment-221110302

Think one of the reasons for suggesting darker anchors was for them only to be on h2s (atm on all) to help differentiate from h3s. I was confused reading the first page of

http://guide.meteor.com/ui-ux.html

because I didn't notice that "view layers" was a different size from "syntax". Perhaps also font weight and/or size.

![image](https://cloud.githubusercontent.com/assets/251288/15759043/2840022c-28db-11e6-98a1-9c414e4ff653.png)

**Comment by dominicnguyen** [comment]
The heading are better differentiated in the upcoming theme update on the [`apollo`](https://github.com/meteor/hexo-theme-meteor/tree/apollo) branch.

**Comment by abernix** [comment]
Things are better, yes! (Thanks, @domyen)

Seen in the wild at: https://theme-example.netlify.com/apollo-hexo-config/styles.html, and saving you a click right here:

![image](https://user-images.githubusercontent.com/841294/38091693-f8756924-336e-11e8-9d96-1fb28a2e7931.png)


Thanks for reporting, @lorensr.
