### ISSUE TITLE
Place the current Meteor Version in the docs

### ISSUE THREAD

**Issue by nerdmed** [meteor/hexo-theme-meteor#18]
@dominicnguyen i am not quite sure if i got this right to place visual feedback for the docs here.
As i read in the forums something about Metoer 1.3.3 i was looking to find the current meteor version. This was placed very prominent on the old docs page. I was looking on the homepage and the github page without a fast result. I think the docs are a good place for that kind of info.

Maybe we could just place it beside `Meteor API Docs` in the sidebar. What do you think?

**Comment by dominicnguyen** [comment]
This is the right place! Thank you for the well articulated feedback. 

There must've been a regression! We used to show the docs in the sidebar of the new theme as you're suggesting. Let me check in with @tmeasday.

**Comment by nerdmed** [comment]
@dominicnguyen @tmeasday i have just noticed that the guide has a [version control](http://guide.meteor.com/) in the sidebar:  

<img width="333" alt="bildschirmfoto 2016-06-15 um 02 51 00" src="https://cloud.githubusercontent.com/assets/3820220/16064730/12a32f8e-32a4-11e6-9d1b-d085ebbe6365.png">

I would imagine it at the exact same position for the docs and at least with the detailed version code of the current meteor release.

**Comment by tmeasday** [comment]
This is now resolved.

**Comment by nerdmed** [comment]
👍
