### ISSUE TITLE
Formatting issues for field names/types

### ISSUE THREAD

**Issue by tmeasday** [meteor/hexo-theme-meteor#20]
See https://github.com/meteor/docs/issues/53

**Comment by lorensr** [comment]
See also https://github.com/meteor/docs/issues/41 and https://github.com/meteor/docs/issues/57

**Comment by lorensr** [comment]
Before:

![image](https://cloud.githubusercontent.com/assets/251288/17067395/8a5ef50c-5019-11e6-8233-060bd3ffef98.png)


After:

![image](https://cloud.githubusercontent.com/assets/251288/17067380/758d0d4e-5019-11e6-85f2-16c60ed96244.png)

**Comment by tmeasday** [comment]
Thanks for sorting this out @lorensr
