### ISSUE TITLE
Link readibility

### ISSUE THREAD

**Issue by lorensr** [meteor/hexo-theme-meteor#22]
This underlining makes it harder for me to read the letters. Maybe no underline or move the line down a little?

![image](https://cloud.githubusercontent.com/assets/251288/16791673/5111ace0-488f-11e6-9c83-b882d3fa06a6.png)

**Comment by dominicnguyen** [comment]
Thanks Loren, I removed underline in the upcoming theme update on the [`apollo`](https://github.com/meteor/hexo-theme-meteor/tree/apollo) branch.

**Comment by abernix** [comment]
Thanks for reporting, @lorensr. This is fixed thanks to @domyen's changes, which I think have finally surfaced everywhere — two years later. 🙇 

### Meteor (Live @ https://theme-example.netlify.com/meteor-hexo-config/)
![image](https://user-images.githubusercontent.com/841294/38078673-b9f07f96-3345-11e8-867a-3d980771e81f.png)

### Apollo (Live @ https://theme-example.netlify.com/apollo-hexo-config/)
![image](https://user-images.githubusercontent.com/841294/38078740-e6031698-3345-11e8-8c0c-ddf5c9d54750.png)
