### ISSUE TITLE
Styling issue in code snippets with no specified language

### ISSUE THREAD

**Issue by stubailo** [meteor/hexo-theme-meteor#25]
https://www.dropbox.com/s/jcb0ikwdycdedvv/Screenshot%202016-08-27%2012.14.10.png?dl=0

**Comment by lorensr** [comment]
I find this easier, in case you're unfamiliar ☺️

cmd-shift-ctrl-4
click & drag
cmd-v inside GH issue

**Comment by tmeasday** [comment]
This code snippet thing seems to be a bug introduced in a patch version of hexo. I've been constraining the hexo version to fix it.

**Comment by tmeasday** [comment]
Fixed via: https://github.com/meteor/guide/commit/ed8224736d06360147cf05d56eb7a234705d2ea2 (if you guys see similar problems in other repos)

**Comment by stubailo** [comment]
@lorensr that's how I got this link - I use a thing that uploads all screenshots to Dropbox. Does GitHub accept pasting of raw image data somehow?

**Comment by lorensr** [comment]
Yep! Think you did cmd-shift-4. Adding the `ctrl` to the first key combo puts raw image on clipboard.

**Comment by lorensr** [comment]
can also paste into some other things – gmail, gdocs, trello cards, slack, forget what else
