### ISSUE TITLE
Code blocks remove empty lines

### ISSUE THREAD

**Issue by lorensr** [meteor/hexo-theme-meteor#30]
this code:

![image](https://cloud.githubusercontent.com/assets/251288/19099913/a6518514-8a88-11e6-85b9-baa69c68cad0.png)

becomes:

![image](https://cloud.githubusercontent.com/assets/251288/19099919/abf745c6-8a88-11e6-94cd-68c6e879d3d7.png)

http://dev.apollodata.com/core/meteor.html#Client

**Comment by tmeasday** [comment]
@lorensr this is a bug in hexo AFAICT. Sticking to the 3.2.0 version of hexo seems to avoid it.

**Comment by lorensr** [comment]
So we should change this line? https://github.com/apollostack/core-docs/blob/master/package.json#L9

**Comment by tmeasday** [comment]
Maybe this one: https://github.com/apollostack/core-docs/blob/master/package.json#L6 (or both)

**Comment by lorensr** [comment]
Thanks, works

![image](https://cloud.githubusercontent.com/assets/251288/19100383/6b4bcd22-8a8c-11e6-9c7b-eb67bb9d7c68.png)
