### ISSUE TITLE
Empty lines in code snippets are not displayed

### ISSUE THREAD

**Issue by stubailo** [meteor/hexo-theme-meteor#41]

**Comment by lorensr** [comment]
Either out-of-date submodule or regression (was fixed in #30)

**Comment by stubailo** [comment]
Looks like this is the fix: https://github.com/hexojs/hexo-theme-landscape/commit/ad0c9e95a13d33c12ffa257d44047b38a38fed6d

**Comment by stubailo** [comment]
I applied a fix to the Apollo branch
