### ISSUE TITLE
offset header on deep link

### ISSUE THREAD

**Issue by thepwagner** [meteor/hexo-theme-meteor#45]
As a content author,
I want to link to a particular section of a page like https://www.apollographql.com/docs/engine/setup-node.html#enabling-compression ,
So that I can go directly to relevant documentation.

The header bar is in front of the background text, which hides the link anchor and makes the user confused about the link they followed.

**Comment by abernix** [comment]
I'll be visiting some docs stuff next week and will try to take a look at this.  I believe I've seen some code, somewhere which was meant to address this, but I may be conjuring that image up.

**Comment by glasser** [comment]
I think this is now fixed. The particular link above doesn't work any more, but this one does.  https://www.apollographql.com/docs/engine/setup-node.html#apollo-engine
