### ISSUE TITLE
Default rendering for markdown doesn't match GitHub README

### ISSUE THREAD

**Issue by stubailo** [meteor/hexo-theme-meteor#48]
By default we have the `marked.breaks` config set to true, which matches the way github renders comment markdown, but not README markdown. Since these files are more likely to be viewed in that way, we should probably set `marked.breaks: false` by default in the theme.

See this commit: https://github.com/apollographql/apollo-link/pull/340/commits/f6be768652e8de4412a5c7668ea366c3e80194f2

**Comment by abernix** [comment]
Note to self: Once all the Apollo repos are using `apollo-hexo-config`, this can be closed thanks to https://github.com/apollographql/apollo-hexo-config/blob/master/_config.yml

**Comment by abernix** [comment]
Done per my above comment (as all deployments are now using `apollo-hexo-config`).
