### ISSUE TITLE
Improve touch menu closing

### ISSUE THREAD

**Issue by lorensr** [meteor/hexo-theme-meteor#5]
- open in chrome iOS: http://docs.meteor.com/api/accounts.html#Meteor-userId
- open menu
- try to close menu by swiping from the right side of the screen
- instead, content scrolls horizontally 

![2016-05-19 16 41 19](https://cloud.githubusercontent.com/assets/251288/15408981/cb4cf570-1de0-11e6-9f79-ca45e5fbff1f.png)

**Comment by lorensr** [comment]
On some pages you can swipe the menu closed, but the header doesn't go back into place:

![2016-05-19 16 47 53](https://cloud.githubusercontent.com/assets/251288/15409159/9700f3b0-1de1-11e6-8e5a-e3230ae62619.png)

**Comment by dominicnguyen** [comment]
The scrolling issue is now fixed. I'll use #6 to record the swipe to open/close enhancement. Thanks for the screenshots, much appreciated! Closing this now.

**Comment by lorensr** [comment]
@dominicnguyen welcome, nice redesign :) 

I'm still able to horizontally scroll on api/accounts.html (1st shot above)
