### ISSUE TITLE
Sometimes menu doesn't appear in iOS chrome

### ISSUE THREAD

**Issue by lorensr** [meteor/hexo-theme-meteor#7]
![2016-05-19 16 49 50](https://cloud.githubusercontent.com/assets/251288/15409205/c8dd3844-1de1-11e6-9b98-a7add25f88c6.png)

**Comment by dominicnguyen** [comment]
Thank you, this should now be fixed in production. Mind confirming again?

**Comment by lorensr** [comment]
Think so :)
