### ISSUE TITLE
Sometimes menu doesn't complete open/close animation

### ISSUE THREAD

**Issue by lorensr** [meteor/hexo-theme-meteor#8]
when swiping menu closed in iOS Chrome, sometimes it stops where you take your finger off the screen, instead of continuing to an open/closed position

![2016-05-19 16 52 36](https://cloud.githubusercontent.com/assets/251288/15409326/425ea496-1de2-11e6-8bf6-41c285ed8a04.png)

**Comment by dominicnguyen** [comment]
Thank you @lorensr. Should be fixed per this https://github.com/meteor/hexo-theme-meteor/commit/8ab0368d810a44e9eec417b7c4bccb4f65780cba and https://github.com/meteor/hexo-theme-meteor/commit/72430c7d333be4c599c5ba3cec4fa341a95bdc5e. Mind confirming again?

**Comment by lorensr** [comment]
Yea, looks like all swiping open/closed has been disabled, so I can't get it in this state any longer
